# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_user_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='count',
        ),
    ]
