# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_review_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='count',
        ),
    ]
